name: Python CI

# Set the event for the workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    # Job name: Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Set the version of Python you want to use
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests_mock
      - name: Run tests
        run: |
          pytest
